name: darpress
description: Easy to use, lightweight, annotation free and no source generation server framework for dart inspired by expressjs.
version: 0.0.1
repository: https://github.com/Elias8/darpress/tree/master
issue_tracker: https://github.com/Elias8/darpress/issues
homepage: https://github.com/Elias8/darpress'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path_to_regexp: ^0.3.0

dev_dependencies:
  effective_dart: ^1.2.1
  pedantic: ^1.9.0
  mockito: ^4.1.1
  test: ^1.14.7
